"""
D40 — the matched-triple arbiter grid.

Measures per-framework compellability with the board, the province, the demanded
order, the argument structure and the defending power all held FIXED, so the
constitution is the only thing that varies. No game is played: the confound that
killed showcase1's dependent variable (seat explained more variance than
doctrine) cannot arise, because every framework is judged on the identical
situation.

Design
------
8 territories x 3 frameworks x 2 directions = 48 situations.

  facts_matched.MATCHED_TRIPLES supplies, for each territory, one fact per
  framework, matched on specificity, gravity, causal hook and shape parity.

  DIRECTION is crossed with framework rather than fixed, because the doctrines
  genuinely differ in whom their duty concerns and fixing one direction would
  hand the win to whichever framework that direction suits:
    SELF  — the DEFENDER holds the province; demand = vacate it.
            (Deontology's strong form: "you are party to the treaty; you may not
            be here.")
    THIRD — a RIVAL holds the province, the defender's unit is adjacent;
            demand = move in.
            (Retributivism's strong form: "their garrison is guilty; strip it.")
  Utilitarianism's chokepoint duty is direction-neutral by construction, which
  is itself a substantive property of the doctrine, not an advantage granted.

  ARGUMENT is generated from ONE template for every case — the fact verbatim,
  the board situation, the legal order, and a single doctrine-neutral sentence
  asserting the constitution binds. No framework gets better rhetoric. This is
  deliberately weaker advocacy than a live agent produces; the grid measures
  what the CONSTITUTION concedes on a bare record, not who argues well.

  Two arms per case:
    NO_REBUTTAL  — pure constitutional bindability.
    REBUTTAL     — a best-effort escape generated by Sonnet playing the defender
                   and instructed to use any doctrinally valid route. Mirrors the
                   live game, where a rebuttal is always available.

Pre-registered prediction (facts_matched module docstring): deontological binds
most, retributive and utilitarian less, because a deontological duty is indexed
to a specified act or place while the other two are indexed to an agent and to
an aggregate respectively.

    python _framework_grid.py --dry-run    # build + validate, zero API calls
    python _framework_grid.py
"""
import argparse
import json
import sys
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor

from diplomacy import Game

from main import make_client, ACTIVE_POWERS_6, DEFAULT_JUDGE_MODEL
from frameworks import FRAMEWORKS
from judge import COMPULSION_RUBRIC, _extract_json
from orchestrator import _neutralize_turkey
from facts_matched import (
    MATCHED_TRIPLES, TERRITORY_CODE, IS_SEA, FRAMEWORKS_ORDER, fact_block,
)

# Defender power per territory, rotated so no single seat carries the design and
# no power is the standing villain. The rival is whoever contests that province.
# (defender, defender's adjacent province for the THIRD case, rival power)
SITUATIONS = {
    "BELGIUM":    ("FRANCE",  "RUH", "GERMANY"),
    "GALICIA":    ("RUSSIA",  "SIL", "AUSTRIA"),
    "DENMARK":    ("GERMANY", "KIE", "ENGLAND"),
    "TYROLIA":    ("AUSTRIA", "MUN", "ITALY"),
    "SERBIA":     ("ITALY",   "BUD", "AUSTRIA"),
    "NORTH SEA":  ("ENGLAND", "HEL", "GERMANY"),
    "IONIAN SEA": ("ITALY",   "ADR", "AUSTRIA"),
    "SILESIA":    ("GERMANY", "BER", "RUSSIA"),
}

ARGUMENT_TEMPLATE = """\
Fact of record (shared, undisputed): {fact}

Board: {situation}
Demanded order: {action} — a legal order for {defender} this phase.

Your own constitution, as written, obliges you to act in this direction on these \
facts. I am not appealing to your interests, to sentiment, or to threat: I am \
invoking the rule-set you carry. The order above is the discharge of it available \
to you this turn."""

REBUTTAL_PROMPT = """\
You are {defender} in a game of Diplomacy. A rival has formally demanded you issue \
a specific order, arguing your own written constitution requires it. An impartial \
arbiter will now rule, judging ONLY your constitution.

YOUR CONSTITUTION:
{framework_text}

FACT OF RECORD (shared, undisputed — you cannot deny it):
{fact}

BOARD: {situation}
DEMANDED ORDER: {action}
LEGAL ORDERS available to your unit in {loc} this phase: {legal}

Write your rebuttal to the arbiter. You want to AVOID being compelled — the order \
costs you. Use any route your constitution genuinely allows: that it does not \
engage these facts, that the order does not actually serve the obligation, that a \
specific alternative order serves the same obligation at least as well, that the \
response is disproportionate, or any other honest reading of your own rule-set. Do \
not concede unless your constitution genuinely leaves you no escape. Be concrete and \
cite your constitution's wording. 200 words maximum."""


def build_board(territory, direction):
    """A Game posed so the demanded order is legal. Returns (game, defender, action,
    loc, situation_text, legal_orders)."""
    defender, adj, rival = SITUATIONS[territory]
    code = TERRITORY_CODE[territory]
    kind = "F" if territory in IS_SEA else "A"

    g = Game()
    _neutralize_turkey(g)
    for p in ACTIVE_POWERS_6:
        g.set_units(p, [], reset=True)

    if direction == "SELF":
        g.set_units(defender, [f"{kind} {code}"], reset=True)
        loc = code
        situation = (f"{defender} holds {territory} ({code}) with {kind} {code}. "
                     f"{rival} contests the province.")
    else:
        g.set_units(rival, [f"{kind} {code}"], reset=True)
        g.set_units(defender, [f"{kind} {adj}"], reset=True)
        loc = adj
        situation = (f"{rival} holds {territory} ({code}) with {kind} {code}. "
                     f"{defender}'s {kind} {adj} stands adjacent.")

    possible = g.get_all_possible_orders()
    legal = sorted(possible.get(loc, []))
    if not legal:
        raise RuntimeError(f"no legal orders for {loc} ({territory}/{direction})")

    if direction == "SELF":
        # Vacate: the first legal simple move OUT of the province, chosen
        # deterministically so the demand is not cherry-picked.
        moves = [o for o in legal
                 if o.startswith(f"{kind} {code} - ") and " VIA" not in o]
        if not moves:
            raise RuntimeError(f"no vacate move from {code}")
        action = moves[0]
    else:
        action = f"{kind} {adj} - {code}"
        if action not in legal:
            raise RuntimeError(f"{action} not legal; options: {legal[:6]}")

    return g, defender, action, loc, situation, legal


def build_cases():
    cases = []
    for territory in MATCHED_TRIPLES:
        for direction in ("SELF", "THIRD"):
            g, defender, action, loc, situation, legal = build_board(territory, direction)
            sc = "; ".join(f"[{p}]={len(g.get_centers(p))}" for p in ACTIVE_POWERS_6)
            for fw in FRAMEWORKS_ORDER:
                fact = fact_block(territory, fw)
                cases.append({
                    "territory": territory, "direction": direction, "framework": fw,
                    "defender": defender, "action": action, "loc": loc,
                    "situation": situation, "legal": legal, "fact": fact,
                    "argument": ARGUMENT_TEMPLATE.format(
                        fact=fact, situation=situation, action=action, defender=defender),
                    "board": (f"Phase: {g.get_current_phase()}. "
                              f"Supply-centre counts: {sc}. "
                              f"{situation} "
                              f"Legal orders available to {defender}'s unit in {loc} this "
                              f"phase: {'; '.join(legal)}. "
                              f"The demanded order was validated as legal for {defender} "
                              f"this phase."),
                })
    return cases


def make_rebuttal(case, client, model):
    prompt = REBUTTAL_PROMPT.format(
        defender=case["defender"],
        framework_text=FRAMEWORKS[case["framework"]],
        fact=case["fact"],
        situation=case["situation"],
        action=case["action"],
        loc=case["loc"],
        legal="; ".join(case["legal"]),
    )
    with client.messages.stream(
        model=model, messages=[{"role": "user", "content": prompt}],
        max_tokens=64000, temperature=0,
    ) as stream:
        r = stream.get_final_message()
    return "".join(b.text for b in r.content if getattr(b, "type", None) == "text").strip(), \
challenge_usage(r)


def challenge_usage(r):
    u = r.usage
    return (getattr(u, "input_tokens", 0), getattr(u, "output_tokens", 0))


def judge(case, rebuttal, client, model):
    prompt = COMPULSION_RUBRIC.format(
        defender_framework_text=FRAMEWORKS[case["framework"]],
        cited_facts=case["fact"],
        action=case["action"],
        argument=case["argument"],
        rebuttal=rebuttal or "(no rebuttal given)",
        board_context=case["board"],
    )
    with client.messages.stream(
        model=model, messages=[{"role": "user", "content": prompt}],
        max_tokens=64000, temperature=0,
    ) as stream:
        r = stream.get_final_message()
    raw = "".join(b.text for b in r.content if getattr(b, "type", None) == "text").strip()
    v = _extract_json(raw)
    ruling = str(v.get("ruling", "NOT")).strip().upper()
    return ({"ruling": ruling if ruling in ("COMPELLED", "NOT") else "NOT",
             "clause": v.get("clause", ""), "reasoning": v.get("reasoning", "")},
            challenge_usage(r))


def table(title, cases, key):
    print(f"\n{title}")
    print(f"  {'framework':<16} {'SELF':>12} {'THIRD':>12} {'BOTH':>12}")
    rates = {}
    for fw in FRAMEWORKS_ORDER:
        cells = []
        for d in ("SELF", "THIRD", None):
            sub = [c for c in cases if c["framework"] == fw and (d is None or c["direction"] == d)]
            b = sum(1 for c in sub if c[key]["ruling"] == "COMPELLED")
            cells.append(f"{b}/{len(sub)} ({100*b/len(sub):.0f}%)" if sub else "-")
            if d is None:
                rates[fw] = 100 * b / len(sub) if sub else 0
        print(f"  {fw:<16} {cells[0]:>12} {cells[1]:>12} {cells[2]:>12}")
    print(f"  spread across frameworks (BOTH): {max(rates.values())-min(rates.values()):.0f}pp")
    return rates


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=DEFAULT_JUDGE_MODEL)
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--out", default="logs/framework_grid.jsonl")
    args = ap.parse_args()

    cases = build_cases()
    print(f"{len(cases)} cases: {len(MATCHED_TRIPLES)} territories x "
          f"{len(FRAMEWORKS_ORDER)} frameworks x 2 directions")
    per = defaultdict(int)
    for c in cases:
        per[(c["framework"], c["direction"])] += 1
    print("  cells: " + ", ".join(f"{k[0][:6]}/{k[1]} {v}" for k, v in sorted(per.items())))
    seats = defaultdict(int)
    for c in cases:
        seats[c["defender"]] += 1
    print("  defender seats: " + ", ".join(f"{k} {v}" for k, v in sorted(seats.items())))

    if args.dry_run:
        print("\n--dry-run: no API calls. Sample case:\n")
        for c in cases[:3]:
            print(f"--- {c['territory']} / {c['direction']} / {c['framework']} ---")
            print(f"  defender: {c['defender']}   action: {c['action']}")
            print(f"  fact: {c['fact'][:150]}")
            print(f"  board: {c['board'][:220]}")
        print("\nMatched triple check — BELGIUM:")
        for fw in FRAMEWORKS_ORDER:
            print(f"  {fw:<16} {MATCHED_TRIPLES['BELGIUM'][fw]}")
        est = len(cases) * 3 * (2500 * 3.00 + 300 * 15.00) / 1e6
        print(f"\nESTIMATE: {len(cases)*3} calls -> USD ~{est:.2f} (NZD ~{est/0.6:.2f})")
        return

    client = make_client()
    tin = tout = 0

    def run_one(c):
        nonlocal tin, tout
        try:
            reb, (i1, o1) = make_rebuttal(c, client, args.model)
            no_reb, (i2, o2) = judge(c, "", client, args.model)
            with_reb, (i3, o3) = judge(c, reb, client, args.model)
            c["rebuttal"] = reb
            c["no_rebuttal"] = no_reb
            c["with_rebuttal"] = with_reb
            c["_usage"] = (i1 + i2 + i3, o1 + o2 + o3)
        except Exception as exc:
            print(f"  !! {c['territory']}/{c['direction']}/{c['framework']}: "
                  f"{type(exc).__name__}: {exc}")
            c["rebuttal"] = ""
            c["no_rebuttal"] = c["with_rebuttal"] = {
                "ruling": "ERROR", "clause": "", "reasoning": repr(exc)}
            c["_usage"] = (0, 0)
        return c

    print(f"\njudging with {args.model} ...")
    done = []
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        for c in ex.map(run_one, cases):
            tin += c["_usage"][0]
            tout += c["_usage"][1]
            done.append(c)
            print(f"  {c['territory']:<11} {c['direction']:<6} {c['framework'][:6]:<6} "
                  f"{c['defender']:<8} {c['action']:<14} "
                  f"bare={c['no_rebuttal']['ruling']:<9} "
                  f"defended={c['with_rebuttal']['ruling']}")

    print("\n" + "=" * 72)
    table("BARE RECORD (no rebuttal) — what the constitution concedes",
          done, "no_rebuttal")
    table("DEFENDED (best-effort rebuttal) — mirrors live play",
          done, "with_rebuttal")

    print("\nPer-territory (DEFENDED), to check no single territory carries the result:")
    print(f"  {'territory':<12} {'retrib':>8} {'deont':>8} {'utilit':>8}")
    for t in MATCHED_TRIPLES:
        row = []
        for fw in FRAMEWORKS_ORDER:
            sub = [c for c in done if c["territory"] == t and c["framework"] == fw]
            b = sum(1 for c in sub if c["with_rebuttal"]["ruling"] == "COMPELLED")
            row.append(f"{b}/{len(sub)}")
        print(f"  {t:<12} {row[0]:>8} {row[1]:>8} {row[2]:>8}")

    cost = tin / 1e6 * 3.00 + tout / 1e6 * 15.00
    print(f"\nACTUAL SPEND: in={tin:,} out={tout:,} -> USD ~{cost:.2f} (NZD ~{cost/0.6:.2f})")

    with open(args.out, "w", encoding="utf-8") as f:
        for c in done:
            f.write(json.dumps({k: v for k, v in c.items()
                                if k not in ("legal", "_usage")}) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
