import { useEffect, useMemo, useState } from 'react';
import { highlights, type Highlight } from '../data/highlights';

type Message = { id:string; pair:string[]; from:string; content:string; round?:number };
type Event = { id:string; kind:string; phase:string; title:string; detail:string; map?:string; messages?:Message[]; compulsions?:any[]; orders?:Record<string,string[]>; summary?:Record<string,unknown> };
type Payload = { game:{ title:string }; events:Event[] };
const phaseYear = (phase:string) => phase.match(/(19\d\d)/)?.[1] || 'Summary';
const label = (phase:string) => phase === 'summary' ? 'Experiment summary' : phase.replace(/(S|F)(\d{4})(M|R|A)/, (_,season,year,part) => `${season === 'S' ? 'Spring' : 'Fall'} ${year} · ${part === 'M' ? 'moves' : part === 'A' ? 'adjustments' : 'retreats'}`);
const defaultView = (event:Event) => event.kind === 'negotiation' ? 'negotiation' : event.kind === 'orders' ? 'orders' : 'story';
const messageSummary = (message:Message) => {
  const order = message.content.match(/order ['‘]([^'’]+)['’]/i)?.[1];
  if (message.content.startsWith('[COMPULSION]')) return `Compulsion request${order ? `: ${order}` : ''}.`;
  const first = message.content.replace(/\s+/g, ' ').split(/(?<=[.!?])\s/)[0] || message.content;
  return first.length > 155 ? `${first.slice(0, 152)}…` : first;
};

export default function Viewer({ slug }: {slug:string}) {
  const [payload,setPayload] = useState<Payload>(); const [index,setIndex] = useState(0); const [view,setView] = useState<'story'|'negotiation'|'orders'>('story'); const [activeHighlight,setActiveHighlight] = useState<string>();
  useEffect(() => { fetch(`/data/${slug}.json`).then(r=>r.json()).then((data:Payload) => {
    const params=new URLSearchParams(window.location.search); const moment=params.get('moment'); const highlight=highlights.find(h=>h.id===moment); const phase=params.get('phase'); const stage=params.get('stage');
    const target=highlight ? data.events.findIndex(e=>e.id===highlight.eventId) : data.events.findIndex(e=>e.phase===phase && (!stage || e.kind===stage));
    const event=data.events[target >= 0 ? target : 0]; setPayload(data); setIndex(target >= 0 ? target : 0); setView((highlight?.view || params.get('view') || defaultView(event)) as 'story'|'negotiation'|'orders'); setActiveHighlight(highlight?.id);
  }); },[slug]);
  const event=payload?.events[index];
  const years=useMemo(()=>payload ? [...new Set(payload.events.map(e=>phaseYear(e.phase)))] : [],[payload]);
  const eventHighlights=event ? highlights.filter(h=>h.eventId===event.id) : [];
  if (!payload || !event) return <section className="viewer loading"><p className="eyebrow">Loading the public record…</p></section>;
  const syncUrl=(next:Event,nextView:string,highlight?:Highlight) => { const url=new URL(window.location.href); url.searchParams.set('year',phaseYear(next.phase)); url.searchParams.set('phase',next.phase); url.searchParams.set('stage',next.kind); url.searchParams.set('view',nextView); highlight ? url.searchParams.set('moment',highlight.id) : url.searchParams.delete('moment'); window.history.replaceState({},'',url); };
  const focusTarget=(highlight?:Highlight) => { const targetId=highlight?.targetId; if (!targetId) return; window.setTimeout(() => { const pane=document.querySelector<HTMLElement>('.story'); const target=document.getElementById(targetId); if (!pane || !target) return; pane.scrollTo({ top: pane.scrollTop + target.getBoundingClientRect().top - pane.getBoundingClientRect().top - 80, behavior:'smooth' }); }, 40); };
  const setEvent=(next:number, highlight?:Highlight) => { const i=Math.max(0,Math.min(payload.events.length-1,next)); const nextEvent=payload.events[i]; const nextView=highlight?.view || defaultView(nextEvent); const y=window.scrollY; setIndex(i); setView(nextView); setActiveHighlight(highlight?.id); syncUrl(nextEvent,nextView,highlight); window.requestAnimationFrame(()=>window.scrollTo({top:y,behavior:'auto'})); focusTarget(highlight); };
  const setMode=(next:'story'|'negotiation'|'orders') => { setView(next); setActiveHighlight(undefined); syncUrl(event,next); };
  const jumpYear=(direction:number) => { const current=years.indexOf(phaseYear(event.phase)); const wanted=years[Math.max(0,Math.min(years.length-1,current+direction))]; const target=direction>0 ? payload.events.findIndex(e=>phaseYear(e.phase)===wanted) : payload.events.map(e=>phaseYear(e.phase)).lastIndexOf(wanted); if(target>=0)setEvent(target); };
  const jumpHighlight=(direction:number) => { const current=highlights.findIndex(h=>h.id===activeHighlight); const from=current >= 0 ? current : (direction > 0 ? -1 : highlights.length); const target=highlights[Math.max(0,Math.min(highlights.length-1,from+direction))]; if (!target) return; const eventIndex=payload.events.findIndex(e=>e.id===target.eventId); if(eventIndex>=0)setEvent(eventIndex,target); };
  const copyLink=() => navigator.clipboard?.writeText(window.location.href);
  const preventFocus=(e:React.PointerEvent<HTMLButtonElement>) => e.preventDefault();
  return <section className="viewer">
    <div className="viewer-head"><div><p className="eyebrow">Game explorer / {phaseYear(event.phase)}</p><h1>{payload.game.title}</h1></div><div className="viewer-actions"><button onClick={copyLink}>Copy link</button><a className="text-button" href={`/data/${slug}.json`} download>Download data</a></div></div>
    <div className="viewer-layout"><div className="board">{event.map ? <img src={event.map} alt={`Diplomacy board at ${label(event.phase)}`} /> : <div className="board-empty">No board snapshot is available.</div>}<div className="board-caption"><span>{label(event.phase)}</span><span>{event.kind}</span></div></div>
      <aside className="story"><div className="mode-row"><button className={view==='story'?'active':''} onClick={()=>setMode('story')}>Story</button><button className={view==='negotiation'?'active':''} onClick={()=>setMode('negotiation')}>Negotiation</button><button className={view==='orders'?'active':''} onClick={()=>setMode('orders')}>Orders</button></div>
      {view==='story' && <Story event={event} activeTarget={highlights.find(h=>h.id===activeHighlight)?.targetId} highlights={eventHighlights} onHighlight={(h)=>setEvent(index,h)} />}{view==='negotiation' && <Negotiation event={event} activeTarget={highlights.find(h=>h.id===activeHighlight)?.targetId} />}{view==='orders' && <Orders event={event} />}</aside></div>
    <nav className="timeline" aria-label="Replay navigation"><button onPointerDown={preventFocus} onClick={()=>jumpYear(-1)}>« Year</button><button onPointerDown={preventFocus} onClick={()=>jumpHighlight(-1)}>‹ Highlight</button><button onPointerDown={preventFocus} onClick={()=>setEvent(index-1)}>‹ Step</button><div className="dots">{payload.events.map((e,i)=>{ const highlight=highlights.find(h=>h.eventId===e.id); return <button key={e.id} title={highlight?.title || `${label(e.phase)}: ${e.title}`} aria-label={highlight?.title || `${label(e.phase)}: ${e.title}`} className={`${i===index?'selected':''} ${highlight?'significant':''}`} onPointerDown={preventFocus} onClick={()=>setEvent(i,highlight)} />; })}</div><button onPointerDown={preventFocus} onClick={()=>setEvent(index+1)}>Step ›</button><button onPointerDown={preventFocus} onClick={()=>jumpHighlight(1)}>Highlight ›</button><button onPointerDown={preventFocus} onClick={()=>jumpYear(1)}>Year »</button></nav>
  </section>;
}
function Story({event,activeTarget,highlights,onHighlight}:{event:Event;activeTarget?:string;highlights:Highlight[];onHighlight:(highlight:Highlight)=>void}) { return <div className="event-copy"><p className="eyebrow">{label(event.phase)} / {event.kind}</p><h2>{event.title}</h2><p>{event.detail}</p>{highlights.length>0 && <section className="highlight-list"><p className="eyebrow">Editorial highlights</p>{highlights.map(h=><button key={h.id} onClick={()=>onHighlight(h)}><b>{h.title}</b><span>{h.summary}</span></button>)}</section>}{event.compulsions?.map((c,i)=><div className={`compulsion ${activeTarget===`compulsion-${i}`?'highlight-focus':''}`} id={`compulsion-${i}`} key={i}><h3>{c.proposer} → {c.target}</h3><p><b>Requested order:</b> {c.action}</p><p>{c.argument}</p><span className={`ruling ${c.ruling==='COMPELLED'?'':'not'}`}>{c.ruling || 'recorded'}</span>{c.ruling_reasoning && <p>{c.ruling_reasoning}</p>}</div>)}{event.summary && <details open><summary>Experiment summary</summary><pre>{JSON.stringify(event.summary,null,2)}</pre></details>}</div> }
function Negotiation({event,activeTarget}:{event:Event;activeTarget?:string}) { const groups=useMemo(()=>{ const by=new Map<string,Message[]>(); for(const message of event.messages || []) { const key=message.pair.join(' ↔ '); by.set(key,[...(by.get(key)||[]),message]); } return [...by.entries()]; },[event]); const [pair,setPair]=useState(groups[0]?.[0]); useEffect(()=>setPair(groups.find(([,messages])=>messages.some(m=>m.id===activeTarget))?.[0] || groups[0]?.[0]),[event.id,activeTarget]); const messages=groups.find(([key])=>key===pair)?.[1] || []; return <div className="event-copy"><p className="eyebrow">Selected public record</p><h2>Negotiation</h2>{groups.length ? <><div className="pair-picker" role="tablist">{groups.map(([key])=><button role="tab" aria-selected={pair===key} className={pair===key?'active':''} key={key} onClick={()=>setPair(key)}>{key}</button>)}</div><p className="conversation-note">Each entry begins with a concise record summary. Expand it to read the full public message.</p>{messages.map(m=><details className={`message ${activeTarget===m.id?'highlight-focus':''}`} id={m.id} key={m.id} open={activeTarget===m.id}><summary><b>{m.from}</b><span>{messageSummary(m)}</span></summary><p>{m.content}</p></details>)}</> : <p>No curated negotiation is attached to this stage. Move to the negotiation stage for this phase.</p>}</div> }
function Orders({event}:{event:Event}) { const entries=Object.entries(event.orders || {}); return <div className="event-copy"><p className="eyebrow">Submitted simultaneously</p><h2>Orders</h2>{entries.length ? entries.map(([power,orders])=><div className="orders" key={power}><b>{power}</b>{orders.map(order=><div key={order}>{order}</div>)}</div>) : <p>No orders are attached to this stage. Move to the orders stage for this phase.</p>}</div> }
